### PR TITLE
Two-DB example

### PR DESCRIPTION
**Pull request by jmpounders**
To run: `python examples/bank_agent_two.py`

UPDATE: This is now chat-about-a-customer.  You enter a customer name and the agent will answer questions continuously about that customer.

TODO:
- Update the clear button to clear message history.  I don't know if that works now or not.

See example questions in gradio app.

~~Note: message history is not preserved between questions.  This can be done with a bit of work, but for now, each question needs to be stand-alone.~~

### CODE REVIEW

**Review by bdzimmer — COMMENTED** [review]
Is my understanding correct that you factored the "simple" agent out into `react_chat.py`? If so, this breaks `bank_agent` and the bank agent evaluation stuff.

**Comment by jmpounders** [comment]
> Is my understanding correct that you factored the "simple" agent out into `react_chat.py`? If so, this breaks `bank_agent` and the bank agent evaluation stuff.

Good call.  Fixed.

**Review by cameronfabbri — APPROVED** [review]
Looks good. It ran for me yesterday but has been hanging this morning, I'm assuming it's just an internet/API issue

**Comment by bdzimmer** [comment]
@jmpounders would like to see a clean merge with `main` before approving

**Comment by jmpounders** [comment]
@bdzimmer Merge conflicts resolved.  Note the refactor of react into react and react_chat affected the eval scripts.  I tested on this version and everything seems to work.

**Pull request merged**
